/*
 * Project Euler: Problem 2
 * 
 * Even Fibonacci numbers:
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5,
 * 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence
 * whose values do not exceed four million, find the sum of the even-valued
 * terms.
 * 
 * Author: Rex Cummings
 * 
 * Date: 01/20/16
 */
public class problem2
{
	public static void main(String[] args)
	{
		System.out.println(new problem2().run());
	}

	public int run()
	{
		int a = 0;
		int b = 1;
		int sum = 0;
		int result = 0;

		while (result < 4000000)
		{
			if (result % 2 == 0)
				sum += result;

			result = a + b;
			b = a;
			a = result;
		}

		return sum;
	}
}
