/*
 * Project Euler: Problem 12
 * 
 * Highly divisible triangular number The sequence of triangle numbers is
 * generated by adding the natural numbers. So the 7th triangle number would be
 * 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 * 1: 1 3: 1,3 6: 1,2,3,6 10: 1,2,5,10 15: 1,3,5,15 21: 1,3,7,21 28:
 * 1,2,4,7,14,28 We can see that 28 is the first triangle number to have over
 * five divisors.
 * 
 * What is the value of the first triangle number to have over five hundred
 * divisors?
 * 
 * Author: Rex Cummings
 * 
 * Date: 02/01/16
 */
public class problem12
{
	private final static int MAX = 500;

	public static void main(String[] args)
	{
		System.out.println(new problem12().run());
	}

	public int run()
	{
		int cnt = 0;
		int size = 0;
		int result = 0;
		boolean check = true;

		while (check)
		{
			cnt++;
			result += cnt;
			size = countFactors(result);
			if (size > MAX)
				check = false;
		}
		return result;
	}

	/*
	 * factors - Counts the number of factors a number has.
	 */
	private static int countFactors(int n)
	{
		int count = 0;
		int j = (int) Math.sqrt(n); // Increase efficiency
		for (int i = 1; i < j; i++)
			if (n % i == 0)
				count++;
		return 2 * count; // Double to make up for sqrt(n)
	}
}
